name = "workers-queue-demo"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-15"

kv_namespaces = [
  # REPLACE THE LINE BELOW WITH THE OUTPUT OF `wrangler kv:namespace create QUEUES_KV`
  { binding = "QUEUES_KV", id = "baf085c23c83436ca3b54751860dea7f" },
]

[build]
command = "npm install && npm run build && npm run test"

[build.upload]
format = "modules"
dir = "dist/src"
main = "./index.mjs"

[durable_objects]
bindings = [{ name = "QUEUE", class_name = "Queue" }]

[[migrations]]
tag = "v1"              # Should be unique for each entry
new_classes = ["Queue"]
